<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var $block \Magento\Catalog\Block\Product\View */
?>
<?php $_product = $block->getProduct(); ?>
<?php $buttonTitle = __('Add to Cart'); ?>
<?php if ($_product->isSaleable()) :?>
<div class="box-tocart">
    <div class="fieldset">
        <?php if ($block->shouldRenderQuantity()) :?>
        <div class="field qty">
            <label class="label" for="qty"><span><?= $block->escapeHtml(__('Qty')) ?></span></label>
            <div class="control">
                <input type="number"
                       name="qty"
                       id="qty"
                       min="0"
                       value="<?= $block->getProductDefaultQty() * 1 ?>"
                       title="<?= $block->escapeHtmlAttr(__('Qty')) ?>"
                       class="input-text qty"
                       data-validate="<?= $block->escapeHtmlAttr(json_encode($block->getQuantityValidators())) ?>"
                       />
            </div>
        </div>
 

<h2>Subscription Details</h2>
   <div class="fieldset">
       <label class="label" for="title"><?php echo __('Subscription') ?><sup>*</sup></label>
        <select id="title" name="subscription" required>
         <?php $config = \Magento\Framework\App\ObjectManager::getInstance()
                    ->get(\Magento\Framework\App\Config\ScopeConfigInterface::class)
                                               ->getValue('subscription/general/interval',\Magento\Store\Model\ScopeInterface::SCOPE_STORE); ?>
            <?php $values = (array)json_decode($config , true);
                            foreach($values as $value =>$row)
                             {?>
                <option value="<?=$row['intervallabel']?>"><?=$row['intervallabel']?></option>    
                            <?php }     ?>
        </select>
    </div>

    <?php endif; ?>
        <div class="actions">
            <button type="submit"
                    title="<?= $block->escapeHtmlAttr($buttonTitle) ?>"
                    class="action primary tocart"
                    id="product-addtocart-button" disabled>
                <span><?= $block->escapeHtml($buttonTitle) ?></span>
            </button>
            <?= $block->getChildHtml('', true) ?>
        </div>
    </div>
</div>
<?php endif; ?>
<script type="text/x-magento-init">
    {
        "#product_addtocart_form": {
            "Magento_Catalog/js/validate-product": {}
        }
    }
</script>